name: Relato de bug
description: Descreva um bug
title: "Relato de bug"
labels: ["bug"]
project:
assignees:
  - octocat
body:
  - type: textarea
    id: Description
    attributes:
      label: Descrição
      description: Descreva o bug de maneira simples.
      placeholder: Placeholder
      value: "Descrição..."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Passos para reproduzir o bug
      description: "Como é possível reproduzir o bug? Descreva no passo a passo."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Em qual navegador você estava jogando?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
